name: Playwright

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  playwright-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.2'
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - uses: actions/checkout@v3
    - name: Install PHP dependencies
      run: sudo apt-get -y install gcc make autoconf libc-dev pkg-config libmcrypt-dev
    - name: Install mcrypt
      run: sudo pecl install mcrypt-1.0.1
    - name: add mcrypt extension to php.ini
      run: echo 'extension=mcrypt.so' >> '/etc/php/7.2/cli/php.ini'
    - name: Install Project dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Directory Permissions
      run: chmod -R 777 app/storage bootstrap
    - name: Install dependencies
      run: cd playwright && npm ci
    - name: Install Playwright Browsers
      run: cd playwright && npx playwright install-deps chromium
    - name: Run Playwright tests
      run: cd playwright && npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright/playwright-report/
        retention-days: 30
